services:
  uav-video:
    image: dimaga/video-stream-manager:latest
    container_name: uav-video

    network_mode: host

    restart: no

    volumes:
      - /dev/v4l:/dev/v4l

    privileged: true
